# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macOS-10.15'
variables:
  PLATFORM_VERSION: "13.7"
  _FORCE_LOGS: 1
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'
  displayName: 'Install Python 3.7'

- script: |
    brew tap facebook/fb
    brew install idb-companion
  displayName: Install IDB Companion

- script: |
    python -m pip install --user fb-idb
  displayName: Install IDB

- script: |
    idb_companion --help
    idb --help
  displayName: Verify idb_companion and idb

- script: |
    /bin/bash -c "sudo xcode-select -s /Applications/Xcode_11.7.app/Contents/Developer"
    xcrun simctl list runtimes
  displayName: 'Setup Xcode'

- script: npm install
  displayName: 'Install Node dependencies'

- script: npm test
  displayName: 'Run unit tests'

- script: npm run e2e-test
  displayName: 'Run functional tests'
