# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macOS-11'
variables:
  PLATFORM_VERSION: "15.2"
  _FORCE_LOGS: 1
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'
  displayName: 'Install Python 3.7'

- script: |
    set -e
    brew tap facebook/fb
    brew install idb-companion@1.1.5
    pip3.7 install fb-idb
  displayName: 'Install idb'

- script: |
    /bin/bash -c "sudo xcode-select -s /Applications/Xcode_13.2.app/Contents/Developer"
    xcrun simctl list runtimes
  displayName: 'Setup Xcode'

- script: npm install
  displayName: 'Install Node dependencies'

- script: npm test
  displayName: 'Run unit tests'

- script: npm run e2e-test
  displayName: 'Run functional tests'
